version: '3'

services:
  php:
    image: php:8.1-fpm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - app_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
